checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 3
testLimit: 100000
timeout: 19800 # 5.5 hours

cryticArgs:
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @uniswap/=node_modules/@uniswap/",
  ]
