checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 3
testLimit: 100000
timeout: 19800 # 5.5 hours

# seed: 4060262336601911860
# seed: 8095038812614485619
# seed: -4123322556660662335

cryticArgs:
  [
    # If we add more dependencies they will need to be added as symlinks here!
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @uniswap/=node_modules/@uniswap/",
  ]

# format: 'text'
# solcArgs: "--allow-paths ../**/*.sol"
