name: Test

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: 'Install'
        run: npm ci
        
      - name: 'Compile'
        run: npm run compile
        
      - name: 'Test'
        run: npm test
